// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjmedlilkxmrbacoitio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqbWVkbGlsa3htcmJhY29pdGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzAwNjIsImV4cCI6MjA2NTUwNjA2Mn0.xRHKmoJut_Yj9zMJArfoTVUDexN9SIzOqPSkKDURGfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);